version: 2

jobs:
  build:
    docker:
      - image: person142/latex:latest
    steps:
      - checkout
      - run: |
          mkdir /artifacts
          make
          cp build/*.pdf /artifacts
      - store_artifacts:
          path: /artifacts

